swagger: '2.0'
info:
  title: Sharpener API
  version: 1.0.0

host: indigo.ncats.io
basePath: /sharpener
schemes:
- "https"

paths:

  /create_gene_list:
    post:
      tags:
      - sharpener
      parameters:
      - in: body
        name: query
        description: transformer query
        required: true
        schema:
          type: array
          items:
            type: string

      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/gene_list'
            

  /transformers:
    get:
      tags:
      - sharpener
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/transformer_info'

  /transform:
    post:
      tags:
      - sharpener
      parameters:
      - in: body
        name: query
        description: transformer query
        required: true
        schema:
          $ref: '#/definitions/transformer_query'

      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/gene_list'
            
  /aggregate:
    post:
      tags:
      - sharpener
      parameters:
      - in: body
        name: query
        description: transformer query
        required: true
        schema:
          $ref: '#/definitions/aggregation_query'

      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/gene_list'

definitions:

  transformer_query:
    type: object
    properties:
      name:
        type: string
      gene_list_id:
        type: string
      controls:
        type: array
        items:
          $ref: '#/definitions/property'

  gene_list:
    type: object
    properties:
      gene_list_id:
        type: string
      genes:
        type: array
        items:
          $ref: '#/definitions/gene_info'

  gene_info:
    type: object
    properties:
      gene_id:
        type: string
      attributes:
        type: array
        items:
          $ref: '#/definitions/attribute'
    required: 
      - gene_id

  attribute:
    type: object
    properties:
      name:
        type: string
      value:
        type: string
      source:
        type: string

  property:
    type: object
    properties:
      name:
        type: string
      value:
        type: string

  transformer_info:
    type: object
    properties:
      name:
        type: string
      function:
        type: string
      parameters:
        type: array
        items:
          $ref: '#/definitions/parameter'

  parameter:
    type: object
    properties:
      name:
        type: string
      type:
        type: string
        description: type of a parameter, one of Boolean, int, double, string
      default:
        type: string
      allowed_values: 
        type: array
        items:
          type: string

  aggregation_query:
    type: object
    properties:
      operation:
        type: string
      gene_list_ids:
        type: array
        items:
          type: string
